In [1]:
%%HTML
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
<style>
    h1, h2, h3, h4, p{
        font-family: "Montserrat"!important;
    }
</style>
<center><h1>Лабораторна робота №2</h1>
<h2>Основи роботи з бібліотекою NumPy</h2></center>
<h3>Завдання 1</h3>
<p>Виконати набір вправ. Всі завдання виконати 2 способами:<br>
а) з використанням універсальних функцій бібліотеки NumPy.<br>
b) за допомогою ітеративних конструкцій (з використанням циклів,
спискових включень тощо).<br>
с) для обох випадків підрахувати час виконання скрипту та зробити
висновок.<br><br>
<b>Вар. 5 </b>(3, 5, 7, 9, 10, 12, 14, 15, 21) </p>
<center>
<h4>№3</h4>
</center>
<p>Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в
якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші
елементи дорівнюють 1.</p>
<br>
<p><b>Метод 1</b></p>

In [6]:
%%time
import numpy as np
#n=int(input("Ввод числа n: "))
#m=int(input("Ввод числа m: "))
#r=int(input("Ввод числа r: "))
#c=int(input("Ввод числа c: "))
n,m,r,c=10,10,3,3
a = []
w=1
for q in range(n): 
    a.append([]) # создаем пустую строку
    e=1
    for b in range(m): 
        if(r==w or c==e):
            a[q].append(0) # добавляем очередной элемент в строку
        else:
            a[q].append(1) # добавляем очередной элемент в строку
        e=e+1
        if(e>c):
            e=1
    w=w+1
    if(w>r):
        w=1
for r in a:
    print(r)


[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 1, 1, 0, 1]
Wall time: 979 µs


In [7]:
%%HTML
<p><b>Метод 2</b></p>

In [8]:
%%time
#n=int(input("Ввод числа n: "))
#m=int(input("Ввод числа m: "))
#r=int(input("Ввод числа r: "))
#c=int(input("Ввод числа c: "))
n,m,r,c=10,10,3,3
arr = np.ones((n,n))
arr[(r-1)::r,:] = 0
arr[:,(c-1)::c] = 0
print(arr)

[[1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 1.]]
Wall time: 4 ms


In [4]:
%%HTML
<center>
<h4>№5</h4>
</center>
<p>Вводиться число n. Вивести масив розміру n на n, в якому в рядках
з парними індексами стоять 1, а в інших – 0.</p>
<br>
<p><b>Метод 1</b></p>

In [21]:
%%timeit
#n=int(input("Ввод числа n: "))
n=10
a = []
for q in range(n): 
    a.append([]) # создаем пустую строку
    for b in range(n): 
        if(q%2):
            a[q].append(0) # добавляем очередной элемент в строку
        else:
            a[q].append(1) # добавляем очередной элемент в строку
a

36.5 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
%%HTML
<p><b>Метод 2</b></p>

In [23]:
%%timeit
#n=int(input("Ввод числа n: "))
n=10
arr = np.zeros((n,n))
arr[::2,:] = 1
arr

2.21 µs ± 94.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
%%HTML
<center>
<h4>№7</h4>
</center>
<p>З клавіатури вводиться масив. Замінити всі нульові елементи на -1.</p>
<br>
<p><b>Метод 1</b></p>

In [32]:
#%%timeit
#a = list(map(int,input('Введите значения через пробел: ').split()))
input_a=[99, 6666, 0, 5, 7, 8, 6, 4, 5, 0, 0, 0, 7, 8]
a = list(map(int,input_a))
for q in range(len(a)):
    if(a[q]==0):
        a[q]=-1
a

[99, 6666, -1, 5, 7, 8, 6, 4, 5, -1, -1, -1, 7, 8]

In [322]:
%%HTML
<p><b>Метод 2</b></p>

In [33]:
#%%timeit
#Z = np.asarray(list(map(int,input('Введите значения через пробел: ').split())))
input_a=[99, 6666, 0, 5, 7, 8, 6, 4, 5, 0, 0, 0, 7, 8]
Z = np.asarray(list(map(int,input_a)))
Z = np.where(Z == 0, -1, Z)
Z

array([  99, 6666,   -1,    5,    7,    8,    6,    4,    5,   -1,   -1,
         -1,    7,    8])

In [383]:
%%HTML
<center>
<h4>№9</h4>
</center>
<p>Вводиться число n. Створити масив значень від n до 0.</p>
<br>
<p><b>Метод 1</b></p>

In [36]:
%%timeit
#n=int(input("Ввод числа n: "))
n=10
a=[]
w=n
for b in range(n+1):
    a.append(w) # добавляем очередной элемент в строку
    w=w-1
a

2.92 µs ± 174 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [76]:
%%HTML
<p><b>Метод 2</b></p>

In [38]:
%%timeit
#n=int(input("Ввод числа n: "))
n=10
np.arange(n+1)

1.39 µs ± 76 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [77]:
%%HTML
<center>
<h4>№10</h4>
</center>
<p>Вводиться числа n i m. Створити масив випадкових значень n на m
і обчислити мінімальне, максимальне значення, середнє та середньо
квадратичне відхилення, округлене до 3 знаків після коми</p>
<br>
<p><b>Метод 1</b></p>

In [41]:
#%%timeit
import random
def sr(numbers):
    v=[]
    for c in range(numbers):
        v.append(sum(a[c]) / len(a[c])) 
    return sum(v) / len(v)
def sro(numbers):
    b=[]
    for i in range(numbers):
        b+=list(a[i])
    m = sum(b) / len(b)
    varRes = sum([(xi - m)**2 for xi in b]) / len(b)
    return varRes**2

#n=int(input("Ввод числа n: "))
#m=int(input("Ввод числа m: "))
n,m=5,5
a = []
for q in range(n): 
    a.append([]) # создаем пустую строку
    for b in range(m): 
        a[q].append(round(random.random(),3)) # добавляем очередной элемент в строку
print(" ")
print("мінімум:", min(min(a)))
print("максимум:", max(max(a)))
print("середнє:", round(sr(n),3))
print("середне квадратичне відхилення:", round(sro(n),3))
a

 
мінімум: 0.192
максимум: 0.879
середнє: 0.436
середне квадратичне відхилення: 0.004


[[0.592, 0.48, 0.405, 0.877, 0.087],
 [0.568, 0.08, 0.332, 0.713, 0.03],
 [0.324, 0.192, 0.516, 0.326, 0.253],
 [0.686, 0.413, 0.31, 0.118, 0.707],
 [0.879, 0.2, 0.504, 0.58, 0.73]]

In [451]:
%%HTML
<p><b>Метод 2</b></p>

In [42]:
#%%timeit
#n=int(input("Ввод числа n: "))
#m=int(input("Ввод числа m: "))
n,m=5,5
Z=np.random.random((n,m))
Z=np.around(Z, decimals=3)
print(" ")
print("мінімум:", np.min(Z))
print("максимум:", np.max(Z))
print("середнє:", np.around(Z.mean(), decimals=3))
print("середне квадратичне відхилення:", np.around((np.var(Z)**2), decimals=3))
print(" ")
print(Z)


 
мінімум: 0.028
максимум: 0.962
середнє: 0.428
середне квадратичне відхилення: 0.007
 
[[0.183 0.942 0.458 0.316 0.151]
 [0.934 0.831 0.388 0.393 0.57 ]
 [0.699 0.223 0.311 0.028 0.269]
 [0.35  0.077 0.121 0.309 0.511]
 [0.822 0.962 0.548 0.055 0.247]]


In [169]:
%%HTML
<center>
<h4>№12</h4>
</center>
<p>Створити масив одиниць розміром n х n та створити в ньому
«рамку», сформовану з 0.</p>
<br>
<p><b>Метод 1</b></p>

In [45]:
%%timeit
#n=int(input("Ввод числа n: "))
n=10
w=[0] * n
a=[0]
e=[1] * (n-2)
for i in range(n):
    if(i==0 or i==n-1):
        w[i] = [0] * n
    else:
        w[i]=a+e+a
w

6.24 µs ± 277 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [187]:
%%HTML
<p><b>Метод 2</b></p>

In [46]:
%%timeit
n=10
#n=int(input("Ввод числа n: "))
arr = np.ones((n,n))
arr[1:(n-1),1:(n-1)] = 0
arr

4.92 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [188]:
%%HTML
<center>
<h4>№14</h4>
</center>
<p>Розмістити на полі 8х8 нулі та одиниці в шахматному порядку,
використовуючи функцію numpy tile().</p>
<br>
<p><b>Метод 1</b></p>

In [51]:
%%timeit
a =[[0, 1, 0, 1, 0, 1, 0, 1],[1, 0, 1, 0, 1, 0, 1, 0]]
x=np.tile(a, [4, 1])
x

17.1 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [321]:
%%HTML
<p><b>Метод 2</b></p>

In [52]:
%%timeit
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
Z

16.4 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [201]:
%%HTML
<center>
<h4>№15</h4>
</center>
<p>Заповнити парні стовбчики матриці розміром n х n одиницями, а
непарні – нулями.</p>
<br>
<p><b>Метод 1</b></p>

In [53]:
%%timeit
n=10
#n=int(input("Ввод числа n: "))
a = []
for q in range(n): 
    a.append([]) # создаем пустую строку
    for b in range(n): 
        if(b%2):
            a[q].append(1) # добавляем очередной элемент в строку
        else:
            a[q].append(0) # добавляем очередной элемент в строку
a

37.5 µs ± 2.74 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [218]:
%%HTML
<p><b>Метод 2</b></p>

In [55]:
%%timeit
n=10
#n=int(input("Ввод числа n: "))
arr = np.ones((n,n))
arr[:,::2] = 0
arr

4.78 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [219]:
%%HTML
<center>
<h4>№21</h4>
</center>
<p>Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих
елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці
на протилежні за знаком.</p>
<br>
<p><b>Метод 1</b></p>

In [60]:
n=int(input("Ввод числа n: "))
m=int(input("Ввод числа m: "))
a = []
for q in range(n): 
    a.append([]) # создаем пустую строку
    for b in range(n): 
        a[q].append(round(random.randint(0, m),3)) # добавляем очередной элемент в строку
print(a)
b=[]
for i in range(n):
    b+=list(a[i])
e=max(b)
for q in range(n):
    for b in range(n): 
        if(a[q][b]==e):
            a[q][b]=-a[q][b]

a

Ввод числа n: 10
Ввод числа m: 4
[[4, 4, 1, 4, 0, 4, 1, 4, 0, 3], [4, 3, 3, 4, 2, 0, 4, 3, 3, 0], [4, 1, 3, 2, 3, 2, 0, 4, 0, 2], [0, 3, 1, 4, 3, 3, 1, 4, 3, 1], [1, 0, 2, 4, 1, 0, 3, 2, 2, 0], [0, 4, 3, 4, 0, 3, 4, 4, 0, 1], [0, 4, 1, 1, 3, 2, 1, 1, 4, 2], [0, 4, 3, 1, 3, 2, 2, 1, 4, 4], [4, 3, 4, 2, 2, 2, 2, 0, 1, 3], [0, 1, 0, 4, 1, 0, 3, 1, 4, 0]]


[[-4, -4, 1, -4, 0, -4, 1, -4, 0, 3],
 [-4, 3, 3, -4, 2, 0, -4, 3, 3, 0],
 [-4, 1, 3, 2, 3, 2, 0, -4, 0, 2],
 [0, 3, 1, -4, 3, 3, 1, -4, 3, 1],
 [1, 0, 2, -4, 1, 0, 3, 2, 2, 0],
 [0, -4, 3, -4, 0, 3, -4, -4, 0, 1],
 [0, -4, 1, 1, 3, 2, 1, 1, -4, 2],
 [0, -4, 3, 1, 3, 2, 2, 1, -4, -4],
 [-4, 3, -4, 2, 2, 2, 2, 0, 1, 3],
 [0, 1, 0, -4, 1, 0, 3, 1, -4, 0]]

In [249]:
%%HTML
<p><b>Метод 2</b></p>

In [61]:
n=int(input("Ввод числа n: "))
m=int(input("Ввод числа m: "))
Z=np.random.randint(0, m,(n,n))
print(Z)
Zmax=Z.max()
print(Zmax)
Z = np.where(Z == Zmax, -Z, Z)
print(Z)


Ввод числа n: 10
Ввод числа m: 4
[[1 0 1 2 2 2 3 2 2 2]
 [0 0 0 3 2 3 0 1 2 2]
 [3 3 3 3 0 2 2 3 0 0]
 [2 1 3 3 3 0 3 0 3 2]
 [0 0 2 2 0 1 0 3 1 3]
 [0 2 0 3 2 1 0 1 2 2]
 [0 2 2 0 2 1 1 0 2 1]
 [1 2 1 2 2 0 0 0 2 2]
 [3 1 0 3 0 0 1 3 0 0]
 [2 2 0 0 0 1 0 1 2 2]]
3
[[ 1  0  1  2  2  2 -3  2  2  2]
 [ 0  0  0 -3  2 -3  0  1  2  2]
 [-3 -3 -3 -3  0  2  2 -3  0  0]
 [ 2  1 -3 -3 -3  0 -3  0 -3  2]
 [ 0  0  2  2  0  1  0 -3  1 -3]
 [ 0  2  0 -3  2  1  0  1  2  2]
 [ 0  2  2  0  2  1  1  0  2  1]
 [ 1  2  1  2  2  0  0  0  2  2]
 [-3  1  0 -3  0  0  1 -3  0  0]
 [ 2  2  0  0  0  1  0  1  2  2]]


In [464]:
%%html
<h3>Завдання 2</h3>
<p>Розв’язати систему за допомогою формул Крамера і виконати перевірку за
допомогою:<br>
a) матричного множення;<br>
b) оберненої матриці;<br>
c) функції numpy.linalg.solve().<br>
Порівняти всі рішення за допомогою функції numpy.allclose()</p><br>
\begin{cases}x_{1}+3x_{2}+5x_{3}+7x_{4}=12\\3x_{1}+5x_{2}+7x_{3}+x_{4}=0\\5x_{1}+7x_{2}+x_{3}+3x_{4}=4\\7x_{1}+x_{2}+3x_{3}+5x_{4}=16\end{cases}

In [30]:
a = np.array([[1, 3, 5, 7],[3, 5, 7, 1],[5, 7, 1, 3],[7, 1, 3, 5]])
a2= np.array([[12],[0],[4],[16]])
y=np.linalg.det(a)
n=4
for i in range(n):
    a_2=a.copy()
    a_2[:,i:(i+1)]=a2
    print("x",i+1,"=",round((round(np.linalg.det(a_2),2)/y),2))
    Z2=np.around(np.linalg.solve(a,a2), decimals=2)
tt=0
for z in range(4):
    tt=tt+a[0][z]*Z2[:][z]
print("Проверка суммы: ",np.allclose(tt,a2[:][0]))

Z=np.around(np.linalg.solve(a,a2), decimals=2)
print("Проверка numpy.linalg.solve(): ",np.allclose(Z,Z2))

r=np.dot(np.linalg.inv(a),a2)
print("Проверка методом оберненої матриці: ",np.allclose(r,Z2))

x 1 = 1.0
x 2 = -1.0
x 3 = -0.0
x 4 = 2.0
Проверка суммы:  True
Проверка numpy.linalg.solve():  True
Проверка методом оберненої матриці:  True


In [651]:
%%html
<h3>Завдання 3</h3>
<p>Обчислити значення матричного виразу<br>
а) з використанням універсальних функцій бібліотеки NumPy.<br>
b) за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).<br>
с) для обох випадків підрахувати час виконання скрипту та зробити висновок.</p><br>

\[\left(A-B^2\right)\left(2A+B\right), де A=\left(\begin{array}{c}5 & 2 &0\\ 10 & 4 &1\\ 7 & 3 &2\end{array}\right),B=\left(\begin{array}{c}3 & 6 &-1\\ -1 & -2 &0\\ 2 & 1 &3\end{array}\right)\]


<p><b>Метод 1</b></p>

In [62]:
a=np.array([[5, 2, 0],[10, 4, 1],[7, 3, 2]])
b=np.array([[3, 6, -1],[-1, -2, 0],[2, 1, 3]])
answer=np.dot((a-np.linalg.matrix_power(b, 2)),(np.dot(a,2)+b))
print(answer)

32.2 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [660]:
%%html
<p><b>Метод 2</b></p>

In [64]:

A=[[5, 2, 0],[10, 4, 1],[7, 3, 2]]
B=[[3, 6, -1],[-1, -2, 0],[2, 1, 3]]
#B^2
result = []
for i in range(len(B)):
    row = []
    for j in range(len(B)):
        product = 0
        for v in range(len(B[i])):
            product += B[i][v] * B[v][j]
        row.append(product)
    result.append(row)
#A-B^2
result2 = []
for i in range(len(A)):
    row2 = []
    for j in range(len(A)):
        row2.append(A[i][j]-result[i][j])
    result2.append(row2)
#2A        
result3 = []
for i in range(len(A)):
    row3 = []
    for j in range(len(A)):
        row3.append(A[i][j]*2)
    result3.append(row3)
#2A+B       
result4 = []
for i in range(len(A)):
    row4 = []
    for j in range(len(A)):
        row4.append(result3[i][j]+B[i][j])
    result4.append(row4)
result4
#(A-B^2)(2A+B)
result5 = []
for i in range(len(B)):
    row5 = []
    for j in range(len(B)):
        product = 0
        for v in range(len(B[i])):
            product += result2[i][v] * result4[v][j]
        row5.append(product)
    result5.append(row5)
print(result5)

[[91, 64, 32], [257, 146, 1], [-322, -135, -51]]


In [701]:
l=np.array(result5)
print("Проверка: ",np.allclose(answer,l))

Проверка:  True
